'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace DevExpress.MVVM.Demos.Properties
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module CommonResources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CommonResources", GetType(CommonResources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirmación.
        '''</summary>
        Friend ReadOnly Property Confirmation_Caption() As String
            Get
                Return ResourceManager.GetString("Confirmation_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Quieres eliminar este {0}?.
        '''</summary>
        Friend ReadOnly Property Confirmation_Delete() As String
            Get
                Return ResourceManager.GetString("Confirmation_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Haga clic en Aceptar para volver a cargar la entidad y perder los cambios no guardados. Haga clic en Cancelar para continuar editando datos..
        '''</summary>
        Friend ReadOnly Property Confirmation_Reset() As String
            Get
                Return ResourceManager.GetString("Confirmation_Reset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Estás seguro de que deseas restablecer el diseño? Vuelva a abrir esta vista para que surta efecto el nuevo diseño..
        '''</summary>
        Friend ReadOnly Property Confirmation_ResetLayout() As String
            Get
                Return ResourceManager.GetString("Confirmation_ResetLayout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Quieres guardar los cambios?.
        '''</summary>
        Friend ReadOnly Property Confirmation_Save() As String
            Get
                Return ResourceManager.GetString("Confirmation_Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Debe guardar la entidad principal {0} antes de agregar un nuevo registro. ¿Quieres guardarlo ahora?.
        '''</summary>
        Friend ReadOnly Property Confirmation_SaveParent() As String
            Get
                Return ResourceManager.GetString("Confirmation_SaveParent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  *.
        '''</summary>
        Friend ReadOnly Property Entity_Changed() As String
            Get
                Return ResourceManager.GetString("Entity_Changed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  (Borrado).
        '''</summary>
        Friend ReadOnly Property Entity_Deleted() As String
            Get
                Return ResourceManager.GetString("Entity_Deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a  (Nuevo).
        '''</summary>
        Friend ReadOnly Property Entity_New() As String
            Get
                Return ResourceManager.GetString("Entity_New", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error de solicitud de servicio de datos.
        '''</summary>
        Friend ReadOnly Property Exception_DataServiceRequestErrorCaption() As String
            Get
                Return ResourceManager.GetString("Exception_DataServiceRequestErrorCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error de Actualizacion.
        '''</summary>
        Friend ReadOnly Property Exception_UpdateErrorCaption() As String
            Get
                Return ResourceManager.GetString("Exception_UpdateErrorCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error de Validacion.
        '''</summary>
        Friend ReadOnly Property Exception_ValidationErrorCaption() As String
            Get
                Return ResourceManager.GetString("Exception_ValidationErrorCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Advertencia.
        '''</summary>
        Friend ReadOnly Property Warning_Caption() As String
            Get
                Return ResourceManager.GetString("Warning_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Algunos campos contienen datos no válidos. Haga clic en Aceptar para cerrar la página y perder los cambios no guardados. Presione Cancelar para continuar editando datos..
        '''</summary>
        Friend ReadOnly Property Warning_SomeFieldsContainInvalidData() As String
            Get
                Return ResourceManager.GetString("Warning_SomeFieldsContainInvalidData", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
