'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Actividades
    Public Property Id As Integer
    Public Property CodigoAfip As Nullable(Of Integer)
    Public Property Descripcion As String
    Public Property DescripcionAdicional As String

    Public Overridable Property EmpresasActividades As ICollection(Of EmpresasActividades) = New HashSet(Of EmpresasActividades)
    Public Overridable Property Legajos As ICollection(Of Legajos) = New HashSet(Of Legajos)

End Class
