'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Categorias
    Public Property Id As Integer
    Public Property Codigo As Nullable(Of Integer)
    Public Property Descripcion As String
    Public Property CondicionLiquidacion As Nullable(Of Integer)
    Public Property Importe As Nullable(Of Decimal)
    Public Property Adicional1 As Nullable(Of Decimal)
    Public Property Adicional2 As Nullable(Of Decimal)
    Public Property HorasNormales As Nullable(Of Integer)
    Public Property HorasMinimasImponibles As Nullable(Of Integer)
    Public Property DiasMinimosImponibles As Nullable(Of Integer)
    Public Property IdConvenio As Nullable(Of Integer)

    Public Overridable Property Convenios As Convenios
    Public Overridable Property Legajos As ICollection(Of Legajos) = New HashSet(Of Legajos)

End Class
