'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Convenios
    Public Property Id As Integer
    Public Property Codigo As Nullable(Of Integer)
    Public Property Descripcion As String
    Public Property Nombre As String

    Public Overridable Property Categorias As ICollection(Of Categorias) = New HashSet(Of Categorias)
    Public Overridable Property Formulas As ICollection(Of Formulas) = New HashSet(Of Formulas)
    Public Overridable Property Legajos As ICollection(Of Legajos) = New HashSet(Of Legajos)
    Public Overridable Property RecibosPlantillas As ICollection(Of RecibosPlantillas) = New HashSet(Of RecibosPlantillas)

End Class
