'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmpresasActividades
    Public Property Id As Integer
    Public Property IdEmpresa As Nullable(Of Integer)
    Public Property IdActividad As Nullable(Of Integer)
    Public Property Activo As Boolean

    Public Overridable Property Actividades As Actividades
    Public Overridable Property Empresas As Empresas

End Class
