'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empresas
    Public Property Id As Integer
    Public Property Codigo As Nullable(Of Integer)
    Public Property Nombre As String
    Public Property Direccion As String
    Public Property Localidad As String
    Public Property CodigoPostal As Nullable(Of Integer)
    Public Property Id_Provincia As Nullable(Of Integer)
    Public Property Id_TipoClaveUnica As Nullable(Of Integer)
    Public Property ClaveUnica As String
    Public Property Email As String
    Public Property Telefono As String
    Public Property IdTipoEmpresaAfip As Nullable(Of Integer)

    Public Overridable Property Contactos As ICollection(Of Contactos) = New HashSet(Of Contactos)
    Public Overridable Property Provincias As Provincias
    Public Overridable Property Provincias1 As Provincias
    Public Overridable Property TipoClaveUnica As TipoClaveUnica
    Public Overridable Property TipoEmpresaAfip As TipoEmpresaAfip
    Public Overridable Property EmpresasActividades As ICollection(Of EmpresasActividades) = New HashSet(Of EmpresasActividades)
    Public Overridable Property LSDRegistro01 As ICollection(Of LSDRegistro01) = New HashSet(Of LSDRegistro01)

End Class
