'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FormasDePagos
    Public Property Id As Integer
    Public Property Descripcion As String
    Public Property RequiereCBU As Boolean
    Public Property CodigoAfip As Integer

    Public Overridable Property Legajos As ICollection(Of Legajos) = New HashSet(Of Legajos)

End Class
