'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Formulas
    Public Property Id As Integer
    Public Property Codigo As Nullable(Of Integer)
    Public Property IdConcepto As Nullable(Of Integer)
    Public Property IdConvenio As Nullable(Of Integer)
    Public Property Descripcion As String
    Public Property Importe As Nullable(Of Decimal)
    Public Property Cantidad As Nullable(Of Double)
    Public Property FormulaCantidad As String
    Public Property FormulaImporte As String
    Public Property CantidadUnidad As Integer
    Public Property Visible As Boolean
    Public Property Activo As Boolean
    Public Property Orden As Nullable(Of Integer)
    Public Property AfectaMejorSueldo As Boolean
    Public Property AfectaImpuestoGanancia As Boolean
    Public Property SumaAlBasico As Boolean
    Public Property IncluirDescripcionConcepto As Boolean
    Public Property VigenteDesde As Nullable(Of Date)
    Public Property VigenteHasta As Nullable(Of Date)
    Public Property Novedad As Nullable(Of Boolean)
    Public Property CodigoAfip As Nullable(Of Integer)

    Public Overridable Property Conceptos As Conceptos
    Public Overridable Property Convenios As Convenios
    Public Overridable Property Unidades As Unidades
    Public Overridable Property FormulasPeriodos As ICollection(Of FormulasPeriodos) = New HashSet(Of FormulasPeriodos)
    Public Overridable Property FormulaTipoLiquidacion As ICollection(Of FormulaTipoLiquidacion) = New HashSet(Of FormulaTipoLiquidacion)
    Public Overridable Property LegajosConceptosParticulares As ICollection(Of LegajosConceptosParticulares) = New HashSet(Of LegajosConceptosParticulares)
    Public Overridable Property LegajosNovedadesDetalles As ICollection(Of LegajosNovedadesDetalles) = New HashSet(Of LegajosNovedadesDetalles)
    Public Overridable Property RecibosDetalles As ICollection(Of RecibosDetalles) = New HashSet(Of RecibosDetalles)
    Public Overridable Property RecibosPlantillas As ICollection(Of RecibosPlantillas) = New HashSet(Of RecibosPlantillas)

End Class
