'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class IdentificacionEnvio
    Public Property Id As Integer
    Public Property Descripcion As String
    Public Property Abreviacion As String

    Public Overridable Property LSDRegistro01 As ICollection(Of LSDRegistro01) = New HashSet(Of LSDRegistro01)

End Class
