'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LegajosNovedadesDetalles
    Public Property Id As Integer
    Public Property IdLegajoNovedad As Nullable(Of Integer)
    Public Property IdFormula As Nullable(Of Integer)
    Public Property Cantidad As Nullable(Of Double)
    Public Property Importe As Nullable(Of Decimal)
    Public Property Observaciones As String

    Public Overridable Property Formulas As Formulas
    Public Overridable Property LegajosNovedades As LegajosNovedades

End Class
