'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LegajosConceptosParticulares
    Public Property Id As Integer
    Public Property IdLegajo As Nullable(Of Integer)
    Public Property IdFormula As Nullable(Of Integer)
    Public Property IdTipoLiquidacion As Nullable(Of Integer)
    Public Property Cantidad As Nullable(Of Double)
    Public Property Importe As Nullable(Of Decimal)
    Public Property VigenteDesde As Nullable(Of Date)
    Public Property VigenteHasta As Nullable(Of Date)
    Public Property Activo As Boolean

    Public Overridable Property Formulas As Formulas
    Public Overridable Property Legajos As Legajos
    Public Overridable Property TipoLiquidacion As TipoLiquidacion

End Class
