'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Legajos
    Public Property Id As Integer
    Public Property Legajo As Nullable(Of Integer)
    Public Property IdEmpresa As Nullable(Of Integer)
    Public Property Nombres As String
    Public Property Apellidos As String
    Public Property CUIL As String
    Public Property Tareas As String
    Public Property FechaIngreso As Nullable(Of Date)
    Public Property FechaEgreso As Nullable(Of Date)
    Public Property IdConvenio As Nullable(Of Integer)
    Public Property Condicionliquidacion As Nullable(Of Integer)
    Public Property Fueraconvenio As Boolean
    Public Property IdCategoria As Nullable(Of Integer)
    Public Property IdSindicato As Nullable(Of Integer)
    Public Property IdObrasocial As Nullable(Of Integer)
    Public Property Sueldo As Nullable(Of Decimal)
    Public Property Adicional As Nullable(Of Decimal)
    Public Property IdJornada As Nullable(Of Integer)
    Public Property idActividad As Nullable(Of Integer)
    Public Property IdFormaDePago As Nullable(Of Integer)
    Public Property CBU As String
    Public Property Conyuge As Nullable(Of Boolean)
    Public Property Hijos As Nullable(Of Integer)
    Public Property Adherentes As Nullable(Of Integer)
    Public Property Domicilio As String
    Public Property Localidad As String
    Public Property IdProvincia As Nullable(Of Integer)
    Public Property FechaNacimiento As Nullable(Of Date)

    Public Overridable Property Actividades As Actividades
    Public Overridable Property Categorias As Categorias
    Public Overridable Property Convenios As Convenios
    Public Overridable Property FormasDePagos As FormasDePagos
    Public Overridable Property Jornadas As Jornadas
    Public Overridable Property ObrasSociales As ObrasSociales
    Public Overridable Property Provincias As Provincias
    Public Overridable Property Sindicatos As Sindicatos
    Public Overridable Property LegajosConceptosParticulares As ICollection(Of LegajosConceptosParticulares) = New HashSet(Of LegajosConceptosParticulares)
    Public Overridable Property LegajosNovedades As ICollection(Of LegajosNovedades) = New HashSet(Of LegajosNovedades)
    Public Overridable Property Recibos As ICollection(Of Recibos) = New HashSet(Of Recibos)

End Class
