'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LegajosNovedades
    Public Property Id As Integer
    Public Property IdLegajo As Nullable(Of Integer)
    Public Property IdTipoLoquidacion As Nullable(Of Integer)
    Public Property Periodo As String
    Public Property FechaPago As Date
    Public Property DiasTrabajados As Nullable(Of Double)
    Public Property HorasTrabajadas As Nullable(Of Double)
    Public Property DiasVacaciones As Nullable(Of Double)

    Public Overridable Property Legajos As Legajos
    Public Overridable Property TipoLiquidacion As TipoLiquidacion
    Public Overridable Property LegajosNovedadesDetalles As ICollection(Of LegajosNovedadesDetalles) = New HashSet(Of LegajosNovedadesDetalles)

End Class
