'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Liquidaciones
    Public Property Id As Integer
    Public Property IdLegajo As Nullable(Of Integer)
    Public Property IdTipoLiquidacion As Nullable(Of Integer)
    Public Property Periodo As Nullable(Of Date)
    Public Property Fecha As Nullable(Of Date)
    Public Property Generado As Boolean
    Public Property Impreso As Boolean
    Public Property TotalRemunerativo As Nullable(Of Decimal)
    Public Property TotalNoRemunerativo As Nullable(Of Decimal)
    Public Property TotalDescuento As Nullable(Of Decimal)
    Public Property Jubilacion As Nullable(Of Decimal)
    Public Property Sindicato As Nullable(Of Decimal)
    Public Property ObraSocial As Nullable(Of Decimal)

End Class
