'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LSDRegistro03
    Public Property Id As Integer
    Public Property IdLSDRegistro02 As Nullable(Of Integer)
    Public Property CUIL As String
    Public Property CodigoConcepto As String
    Public Property Cantidad As Nullable(Of Decimal)
    Public Property Unidad As String
    Public Property Importe As Nullable(Of Decimal)
    Public Property DebitoCredito As String
    Public Property PeriodoAjuste As String

    Public Overridable Property LSDRegistro02 As LSDRegistro02

End Class
