'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LSDRegistro02
    Public Property Id As Integer
    Public Property IdLSDRegistro01 As Nullable(Of Integer)
    Public Property CUIL As String
    Public Property Legajo As Nullable(Of Integer)
    Public Property DependenciaRevista As String
    Public Property CBU As String
    Public Property CantDiasProporcionarTope As Nullable(Of Integer)
    Public Property FechaDePago As String
    Public Property FormaDePago As Nullable(Of Integer)

    Public Overridable Property LSDRegistro01 As LSDRegistro01
    Public Overridable Property LSDRegistro03 As ICollection(Of LSDRegistro03) = New HashSet(Of LSDRegistro03)
    Public Overridable Property LSDRegistro04 As ICollection(Of LSDRegistro04) = New HashSet(Of LSDRegistro04)

End Class
