'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LSDRegistro01
    Public Property Id As Integer
    Public Property IdEmpresa As Nullable(Of Integer)
    Public Property IdIdentificacionEnvio As Nullable(Of Integer)
    Public Property Periodo As String
    Public Property IdTipoLiquidacion As Nullable(Of Integer)
    Public Property NumeroDeLiquidacion As Nullable(Of Integer)
    Public Property DiasBases As Nullable(Of Integer)
    Public Property CantidadDeRegistros04 As Nullable(Of Integer)
    Public Property Generado As Boolean

    Public Overridable Property Empresas As Empresas
    Public Overridable Property IdentificacionEnvio As IdentificacionEnvio
    Public Overridable Property TipoLiquidacion As TipoLiquidacion
    Public Overridable Property LSDRegistro02 As ICollection(Of LSDRegistro02) = New HashSet(Of LSDRegistro02)

End Class
