'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LSDRegistro04
    Public Property Id As Integer
    Public Property IdLSDRegistro02 As Nullable(Of Integer)
    Public Property CUIL As String
    Public Property Conyuge As String
    Public Property CantidadHijos As Nullable(Of Integer)
    Public Property CCT As String
    Public Property SCVO As String
    Public Property Reduccion As String
    Public Property TipoEmpresa As String
    Public Property TipoOperacion As String
    Public Property CodigoSituacion As Nullable(Of Integer)
    Public Property CodigoCondicion As Nullable(Of Integer)
    Public Property CodigoActividad As Nullable(Of Integer)
    Public Property CodigoModalidadContratacion As Nullable(Of Integer)
    Public Property CodigoSiniestrado As Nullable(Of Integer)
    Public Property CodigoLocalidad As Nullable(Of Integer)
    Public Property SituacionRevista1 As Nullable(Of Integer)
    Public Property DiaInicioRevista1 As Nullable(Of Integer)
    Public Property SituacionRevista2 As Nullable(Of Integer)
    Public Property DiaInicioRevista2 As Nullable(Of Integer)
    Public Property SituacionRevista3 As Nullable(Of Integer)
    Public Property DiaInicioRevista3 As Nullable(Of Integer)
    Public Property DiasTrabajados As Nullable(Of Integer)
    Public Property HoraaTrabajadas As Nullable(Of Integer)
    Public Property PorcentajeAporteAdicionalSS As Nullable(Of Decimal)
    Public Property ContribucionTareaDiferencial As Nullable(Of Decimal)
    Public Property CodigoObraSocial As String
    Public Property CantidadAdherentes As Nullable(Of Integer)
    Public Property AporteAdicionalOS As Nullable(Of Decimal)
    Public Property ContribucionAdicionalOS As Nullable(Of Decimal)
    Public Property BCDiferencialAporteOSyFSR As Nullable(Of Decimal)
    Public Property BCDiferencialOSyFSR As Nullable(Of Decimal)
    Public Property BCDiferencialLRT As Nullable(Of Decimal)
    Public Property RemuneracionMaternidadAnses As Nullable(Of Decimal)
    Public Property RemuneracionBruta As Nullable(Of Decimal)
    Public Property BaseImponible1 As Nullable(Of Decimal)
    Public Property BaseImponible2 As Nullable(Of Decimal)
    Public Property BaseImponible3 As Nullable(Of Decimal)
    Public Property BaseImponible4 As Nullable(Of Decimal)
    Public Property BaseImponible5 As Nullable(Of Decimal)
    Public Property BaseImponible6 As Nullable(Of Decimal)
    Public Property BaseImponible7 As Nullable(Of Decimal)
    Public Property BaseImponible8 As Nullable(Of Decimal)
    Public Property BaseImponible9 As Nullable(Of Decimal)
    Public Property BCDiferencialAporteSegSocial As Nullable(Of Decimal)
    Public Property BCDiferencialContribSegSocial As Nullable(Of Decimal)
    Public Property BaseImponible10 As Nullable(Of Decimal)
    Public Property ImporteADetraer As Nullable(Of Decimal)

    Public Overridable Property LSDRegistro02 As LSDRegistro02

End Class
