'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Modelo
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Modelo")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Actividades() As DbSet(Of Actividades)
    Public Overridable Property Categorias() As DbSet(Of Categorias)
    Public Overridable Property CodigosDeModalidadDeContratacion() As DbSet(Of CodigosDeModalidadDeContratacion)
    Public Overridable Property CodigosDeRevistas() As DbSet(Of CodigosDeRevistas)
    Public Overridable Property CodigosDeSiniestrados() As DbSet(Of CodigosDeSiniestrados)
    Public Overridable Property Conceptos() As DbSet(Of Conceptos)
    Public Overridable Property Contactos() As DbSet(Of Contactos)
    Public Overridable Property Convenios() As DbSet(Of Convenios)
    Public Overridable Property Empresas() As DbSet(Of Empresas)
    Public Overridable Property EmpresasActividades() As DbSet(Of EmpresasActividades)
    Public Overridable Property FormasDePagos() As DbSet(Of FormasDePagos)
    Public Overridable Property Formulas() As DbSet(Of Formulas)
    Public Overridable Property FormulasPeriodos() As DbSet(Of FormulasPeriodos)
    Public Overridable Property FormulaTipoLiquidacion() As DbSet(Of FormulaTipoLiquidacion)
    Public Overridable Property IdentificacionEnvio() As DbSet(Of IdentificacionEnvio)
    Public Overridable Property Jornadas() As DbSet(Of Jornadas)
    Public Overridable Property Legajos() As DbSet(Of Legajos)
    Public Overridable Property LegajosConceptosParticulares() As DbSet(Of LegajosConceptosParticulares)
    Public Overridable Property LegajosNovedades() As DbSet(Of LegajosNovedades)
    Public Overridable Property LegajosNovedadesDetalles() As DbSet(Of LegajosNovedadesDetalles)
    Public Overridable Property LSDRegistro01() As DbSet(Of LSDRegistro01)
    Public Overridable Property LSDRegistro02() As DbSet(Of LSDRegistro02)
    Public Overridable Property LSDRegistro03() As DbSet(Of LSDRegistro03)
    Public Overridable Property LSDRegistro04() As DbSet(Of LSDRegistro04)
    Public Overridable Property Meses() As DbSet(Of Meses)
    Public Overridable Property Modulos() As DbSet(Of Modulos)
    Public Overridable Property ObrasSociales() As DbSet(Of ObrasSociales)
    Public Overridable Property Operaciones() As DbSet(Of Operaciones)
    Public Overridable Property Operaciones_Modulos() As DbSet(Of Operaciones_Modulos)
    Public Overridable Property OrigenCalculoLS() As DbSet(Of OrigenCalculoLS)
    Public Overridable Property ParametrosLibroDeSueldo() As DbSet(Of ParametrosLibroDeSueldo)
    Public Overridable Property ParametrosLibroDeSueldoDetalle() As DbSet(Of ParametrosLibroDeSueldoDetalle)
    Public Overridable Property Provincias() As DbSet(Of Provincias)
    Public Overridable Property Recibos() As DbSet(Of Recibos)
    Public Overridable Property RecibosDetalles() As DbSet(Of RecibosDetalles)
    Public Overridable Property RecibosPlantillas() As DbSet(Of RecibosPlantillas)
    Public Overridable Property Roles() As DbSet(Of Roles)
    Public Overridable Property Roles_Modulos_Operaciones() As DbSet(Of Roles_Modulos_Operaciones)
    Public Overridable Property Roles_Operaciones() As DbSet(Of Roles_Operaciones)
    Public Overridable Property Sindicatos() As DbSet(Of Sindicatos)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property TipoClaveUnica() As DbSet(Of TipoClaveUnica)
    Public Overridable Property TipoConceptos() As DbSet(Of TipoConceptos)
    Public Overridable Property TipoEmpresaAfip() As DbSet(Of TipoEmpresaAfip)
    Public Overridable Property TipoLiquidacion() As DbSet(Of TipoLiquidacion)
    Public Overridable Property Unidades() As DbSet(Of Unidades)
    Public Overridable Property Usuarios() As DbSet(Of Usuarios)
    Public Overridable Property Variables() As DbSet(Of Variables)
    Public Overridable Property Liquidaciones() As DbSet(Of Liquidaciones)

End Class
