'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ObrasSociales
    Public Property Id As Integer
    Public Property Codigo As String
    Public Property Nombre As String
    Public Property Direccion As String
    Public Property Localidad As String
    Public Property CodigoPostal As Nullable(Of Integer)
    Public Property IdProvincia As Nullable(Of Integer)
    Public Property Email As String
    Public Property Telefono As String
    Public Property PorcientoAporte As Nullable(Of Double)
    Public Property PorcientoRetencion As Nullable(Of Double)
    Public Property ImporteAporte As Nullable(Of Decimal)
    Public Property ImporteRetencion As Nullable(Of Decimal)
    Public Property BaseDeCalculo As String

    Public Overridable Property Legajos As ICollection(Of Legajos) = New HashSet(Of Legajos)
    Public Overridable Property Provincias As Provincias

End Class
