'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Operaciones_Modulos
    Public Property Id As Integer
    Public Property IdOperacion As Nullable(Of Integer)
    Public Property IdModulo As Nullable(Of Integer)

    Public Overridable Property Roles_Operaciones As ICollection(Of Roles_Operaciones) = New HashSet(Of Roles_Operaciones)

End Class
