'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ParametrosLibroDeSueldoDetalle
    Public Property Id As Integer
    Public Property IdParametrosLibroDeSueldo As Integer
    Public Property Tabla As String
    Public Property Campo As String

End Class
