'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Provincias
    Public Property Id As Integer
    Public Property Codigo As String
    Public Property Nombre As String

    Public Overridable Property Empresas As ICollection(Of Empresas) = New HashSet(Of Empresas)
    Public Overridable Property Empresas1 As ICollection(Of Empresas) = New HashSet(Of Empresas)
    Public Overridable Property Legajos As ICollection(Of Legajos) = New HashSet(Of Legajos)
    Public Overridable Property ObrasSociales As ICollection(Of ObrasSociales) = New HashSet(Of ObrasSociales)
    Public Overridable Property Sindicatos As ICollection(Of Sindicatos) = New HashSet(Of Sindicatos)

End Class
