'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Recibos
    Public Property Id As Integer
    Public Property IdEmpresa As Nullable(Of Integer)
    Public Property IdLegajo As Nullable(Of Integer)
    Public Property Fecha As Nullable(Of Date)
    Public Property Periodo As String
    Public Property IdTipoLiquidacion As Nullable(Of Integer)
    Public Property TotalRemunerativos As Nullable(Of Decimal)
    Public Property TotalNoRemunerativos As Nullable(Of Decimal)
    Public Property TotalDescuentos As Nullable(Of Decimal)
    Public Property Total As Nullable(Of Decimal)
    Public Property FechaPago As Date

    Public Overridable Property Legajos As Legajos
    Public Overridable Property RecibosDetalles As ICollection(Of RecibosDetalles) = New HashSet(Of RecibosDetalles)

End Class
