'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RecibosDetalles
    Public Property Id As Integer
    Public Property IdRecibo As Nullable(Of Integer)
    Public Property IdConcepto As Nullable(Of Integer)
    Public Property formulaCantidad As String
    Public Property formulaImporte As String
    Public Property Activo As Boolean
    Public Property FechaDesde As Nullable(Of Date)
    Public Property FechaHasta As Nullable(Of Date)
    Public Property Cantidad As Nullable(Of Decimal)
    Public Property Importe As Nullable(Of Double)
    Public Property Remunerativo As Nullable(Of Decimal)
    Public Property Descuento As Nullable(Of Decimal)
    Public Property NoRemunerativo As Nullable(Of Decimal)

    Public Overridable Property Formulas As Formulas
    Public Overridable Property Recibos As Recibos

End Class
