'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RecibosPlantillas
    Public Property Id As Integer
    Public Property IdConvenio As Integer
    Public Property IdTipoLiquidacion As Integer
    Public Property IdFormula As Integer

    Public Overridable Property Convenios As Convenios
    Public Overridable Property Formulas As Formulas
    Public Overridable Property TipoLiquidacion As TipoLiquidacion

End Class
