'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Roles
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property SuperUsuario As Boolean

    Public Overridable Property Roles_Modulos_Operaciones As ICollection(Of Roles_Modulos_Operaciones) = New HashSet(Of Roles_Modulos_Operaciones)
    Public Overridable Property Roles_Operaciones As ICollection(Of Roles_Operaciones) = New HashSet(Of Roles_Operaciones)
    Public Overridable Property Usuarios As ICollection(Of Usuarios) = New HashSet(Of Usuarios)

End Class
