'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Roles_Modulos_Operaciones
    Public Property Id As Integer
    Public Property IdRol As Integer
    Public Property IdModulo As Integer
    Public Property IdOperador As Integer
    Public Property Activo As Boolean

    Public Overridable Property Modulos As Modulos
    Public Overridable Property Operaciones As Operaciones
    Public Overridable Property Roles As Roles

End Class
