'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipoLiquidacion
    Public Property Id As Integer
    Public Property Descripcion As String
    Public Property CodigoAfip As String

    Public Overridable Property FormulaTipoLiquidacion As ICollection(Of FormulaTipoLiquidacion) = New HashSet(Of FormulaTipoLiquidacion)
    Public Overridable Property LegajosConceptosParticulares As ICollection(Of LegajosConceptosParticulares) = New HashSet(Of LegajosConceptosParticulares)
    Public Overridable Property LegajosNovedades As ICollection(Of LegajosNovedades) = New HashSet(Of LegajosNovedades)
    Public Overridable Property LSDRegistro01 As ICollection(Of LSDRegistro01) = New HashSet(Of LSDRegistro01)
    Public Overridable Property RecibosPlantillas As ICollection(Of RecibosPlantillas) = New HashSet(Of RecibosPlantillas)

End Class
