'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property Id As Integer
    Public Property Login As String
    Public Property Nombre As String
    Public Property Email As String
    Public Property Password As String
    Public Property Fecha As Nullable(Of Date)
    Public Property IdRol As Nullable(Of Integer)
    Public Property Rol_Id As Nullable(Of Integer)

    Public Overridable Property Roles As Roles

End Class
