'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.ComponentModel.DataAnnotations
Imports System.ComponentModel.DataAnnotations.Schema

<Table("IdentificacionEnvio")>
Partial Public Class IdentificacionEnvio

    Public Sub New()
        LSDRegistro01 = New HashSet(Of LSDRegistro01)()
    End Sub

    <Key>
    <DatabaseGenerated(DatabaseGeneratedOption.None)>
    Public Property Id As Integer

    <StringLength(150)>
    Public Property Descripcion As String

    <StringLength(2)>
    Public Property Abreviacion As String

    Public Overridable Property LSDRegistro01 As ICollection(Of LSDRegistro01) = New HashSet(Of LSDRegistro01)

End Class
